type Query {
  """
  Returns the user that is currently logged in (if any).
  """
  currentUser: User

  version: String!

  """
  Returns all users that match the given query string.
  If no query string is given, returns suggestions based on the user that is
  currently logged in.
  """
  findUsers(query: String): [User!]!
}
