version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=classifai
    ports:
      - 5432:5432

volumes:
  dbdata:
