export { ReactComponent as SelectIcon } from "./select.svg";
export { ReactComponent as EraserIcon } from "./eraser-ar.svg";
export { ReactComponent as DeleteIcon } from "./delete.svg";
export { ReactComponent as ClearIcon } from "./clear.svg";
export { ReactComponent as InvertSelectionIcon } from "./invertSelection.svg";
export { ReactComponent as UndoIcon } from "./undo-ar.svg";
export { ReactComponent as RedoIcon } from "./redo-ar.svg";
export { ReactComponent as CrosshairPointer } from "./crosshairPointer.svg";
export { ReactComponent as SettingsIcon } from "./settings-ar.svg";
