/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Job } from "./job";
/**
 *
 * @export
 * @interface Annotation
 */
export interface Annotation {
  /**
   * The identifier (uuid) of the annotation.
   * @type {string}
   * @memberof Annotation
   */
  id: string;
  /**
   * The path of the annotation file relative to the specified data source location.
   * @type {string}
   * @memberof Annotation
   */
  dataUri: string;
  /**
   * Indicates whether an annotation has been verified by a human.
   * @type {boolean}
   * @memberof Annotation
   */
  verified: boolean;
  /**
   * The identifier of the image (uuid) that the annotation belongs to.
   * @type {string}
   * @memberof Annotation
   */
  image: string;
  /**
   * The identifier of the job (uuid) that created the annotation. This field may be `null` if the annotation was not automatically created by a job.
   * @type {Job}
   * @memberof Annotation
   */
  job: Job;
  /**
   * The date and time the annotation was created.
   * @type {Date}
   * @memberof Annotation
   */
  createdAt: Date;
  /**
   * The date and time the annotation was last updated.
   * @type {Date}
   * @memberof Annotation
   */
  updatedAt: Date;
}
