/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateAnnotationDto
 */
export interface CreateAnnotationDto {
  /**
   * The identifier of the image (uuid) that the annotation will belong to.
   * @type {string}
   * @memberof CreateAnnotationDto
   */
  image: string;
  /**
   * The identifier of the job (uuid) that the annotation was created by.
   * @type {string}
   * @memberof CreateAnnotationDto
   */
  job?: string;
  /**
   * The path of the annotation file relative to the specified data source location.
   * @type {string}
   * @memberof CreateAnnotationDto
   */
  dataUri: string;
  /**
   * Indicates whether an annotation has been verified by a human. Set to false by default.
   * @type {boolean}
   * @memberof CreateAnnotationDto
   */
  verified?: boolean;
  /**
   * The annotation file. Should be passed if the file is not already present in the data source.
   * @type {Blob}
   * @memberof CreateAnnotationDto
   */
  file?: Blob;
}
