/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateImageDto
 */
export interface CreateImageDto {
  /**
   * The identifier of the dataset (uuid) that the image will belong to.
   * @type {string}
   * @memberof CreateImageDto
   */
  dataset: string;
  /**
   * The path of the image file relative to the specified data source location.
   * @type {string}
   * @memberof CreateImageDto
   */
  dataUri: string;
  /**
   * The image file. Should be passed if the file is not already present in the data source.
   * @type {Blob}
   * @memberof CreateImageDto
   */
  file: Blob;
}
