/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateJobDto
 */
export interface CreateJobDto {
  /**
   * The name of the model that will be used to annotate images.
   * @type {string}
   * @memberof CreateJobDto
   */
  modelName: string;
  /**
   * The version of the model that will be used to annotate images.
   * @type {string}
   * @memberof CreateJobDto
   */
  modelVersion: string;
  /**
   * The identifier of the project (uuid) that the job will belong to.
   * @type {string}
   * @memberof CreateJobDto
   */
  project: string;
  /**
   * A list of the images that should be annotated. Each image is represented by its identifier (uuid).
   * @type {Array<string>}
   * @memberof CreateJobDto
   */
  images: Array<string>;
}
