/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DeleteAllDto
 */
export interface DeleteAllDto {
  /**
   * The UUIDs of the objects to be deleted.
   * @type {Array<string>}
   * @memberof DeleteAllDto
   */
  ids: Array<string>;
}
