/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Image
 */
export interface Image {
  /**
   * The identifier (uuid) of the image.
   * @type {string}
   * @memberof Image
   */
  id: string;
  /**
   * The path of the image file relative to the specified data source location.
   * @type {string}
   * @memberof Image
   */
  dataUri: string;
  /**
   * The identifier of the dataset (uuid) that the image belongs to.
   * @type {string}
   * @memberof Image
   */
  dataset: string;
  /**
   * The date and time the image was created.
   * @type {Date}
   * @memberof Image
   */
  createdAt: Date;
  /**
   * The date and time the image was last updated.
   * @type {Date}
   * @memberof Image
   */
  updatedAt: Date;
}
