/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Job
 */
export interface Job {
  /**
   * The identifier (uuid) of the job.
   * @type {string}
   * @memberof Job
   */
  id: string;
  /**
   * The name of the project to which the job belongs.
   * @type {string}
   * @memberof Job
   */
  project: string;
  /**
   * The name of the model used to annotate the images.
   * @type {string}
   * @memberof Job
   */
  modelName: string;
  /**
   * The version of the model used to annotate the images.
   * @type {string}
   * @memberof Job
   */
  modelVersion: string;
  /**
   * The current status of the job. By default it is `queued`, which means that the job is waiting to be processed. When the job is being processed, its status is `running`. When the job is finished, its status is `succeeded` or `failed`. The user can also cancel the job, which will change its status to `canceled`.
   * @type {string}
   * @memberof Job
   */
  status: JobStatusEnum;
  /**
   * The path of the log file of the job.
   * @type {string}
   * @memberof Job
   */
  logFileUri: string;
  /**
   * The date and time at which the processing of the job was started, i.e. the annotation process started. This date will be `null` if the job has not been started.
   * @type {Date}
   * @memberof Job
   */
  startedAt: Date;
  /**
   * The date and time at which the processing of the job was ended, i.e. the annotation process ended. This date will be `null` if the job has not yet finished.
   * @type {Date}
   * @memberof Job
   */
  finishedAt: Date;
  /**
   * The date and time the job was created.
   * @type {Date}
   * @memberof Job
   */
  createdAt: Date;
  /**
   * The date and time the job was last updated.
   * @type {Date}
   * @memberof Job
   */
  updatedAt: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum JobStatusEnum {
  Queued = "queued",
  Running = "running",
  Succeeded = "succeeded",
  Failed = "failed",
  Canceled = "canceled",
}
