/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelVersionTag } from "./model-version-tag";
/**
 *
 * @export
 * @interface ModelVersion
 */
export interface ModelVersion {
  /**
   * The name of the model.
   * @type {string}
   * @memberof ModelVersion
   */
  name: string;
  /**
   * The version of the model.
   * @type {string}
   * @memberof ModelVersion
   */
  version: string;
  /**
   * The description of the model.
   * @type {string}
   * @memberof ModelVersion
   */
  description: string;
  /**
   * The list of model version tags.
   * @type {Array<ModelVersionTag>}
   * @memberof ModelVersion
   */
  tags: Array<ModelVersionTag>;
  /**
   * The date and time the model version was created.
   * @type {Date}
   * @memberof ModelVersion
   */
  createdAt: Date;
  /**
   * The date and time the model version was last updated.
   * @type {Date}
   * @memberof ModelVersion
   */
  updatedAt: Date;
}
