/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Progress
 */
export interface Progress {
  /**
   * The total number of images in progress of being annotated.
   * @type {number}
   * @memberof Progress
   */
  totalImages: number;
  /**
   * The number of annotated images.
   * @type {number}
   * @memberof Progress
   */
  annotatedImages: number;
  /**
   * The number of annotated images that have at least one verified annotation.
   * @type {number}
   * @memberof Progress
   */
  verifiedImages: number;
}
