/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Project
 */
export interface Project {
  /**
   * The identifier (uuid) of the project.
   * @type {string}
   * @memberof Project
   */
  id: string;
  /**
   * The name of the project.
   * @type {string}
   * @memberof Project
   */
  name: string;
  /**
   * The date and time the project was created.
   * @type {Date}
   * @memberof Project
   */
  createdAt: Date;
  /**
   * The date and time the project was last updated.
   * @type {Date}
   * @memberof Project
   */
  updatedAt: Date;
}
