/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateAnnotationDto
 */
export interface UpdateAnnotationDto {
  /**
   * The path of the annotation file relative to the specified data source location.
   * @type {string}
   * @memberof UpdateAnnotationDto
   */
  dataUri?: string;
  /**
   * Indicates whether an annotation has been verified by a human. Set to false by default.
   * @type {boolean}
   * @memberof UpdateAnnotationDto
   */
  verified?: boolean;
  /**
   * The annotation file. Should be passed to update the file referenced by the dataUri.
   * @type {Blob}
   * @memberof UpdateAnnotationDto
   */
  file?: Blob;
}
