/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateImageDto
 */
export interface UpdateImageDto {
  /**
   * The path of the image file relative to the specified data source location.
   * @type {string}
   * @memberof UpdateImageDto
   */
  dataUri: string;
  /**
   * The image file. Should be passed to update the file referenced by the dataUri.
   * @type {Blob}
   * @memberof UpdateImageDto
   */
  file: Blob;
}
