/* tslint:disable */
/* eslint-disable */
/**
 * Annotation Service
 * A service to make medical image annotation as enjoyable as possible.
 *
 * OpenAPI spec version: 0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateJobDto
 */
export interface UpdateJobDto {
  /**
   * The new status of the job. By default, a job is in status `queued`. A valid order of transitions is enforced. For example, when the job is in status `queued`, it can only be updated to `running`, `failed` or `canceled`. From status `running`, it can only be updated to `succeeded`, `failed` or `canceled`.
   * @type {string}
   * @memberof UpdateJobDto
   */
  status?: UpdateJobDtoStatusEnum;
  /**
   * The job log .txt file.
   * @type {Blob}
   * @memberof UpdateJobDto
   */
  file?: Blob;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateJobDtoStatusEnum {
  Queued = "queued",
  Running = "running",
  Succeeded = "succeeded",
  Failed = "failed",
  Canceled = "canceled",
}
