name: Deploy to GitHub Pages (Production)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NX_DEPLOY_URL: /

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile
      - run: yarn build editor editor --prod --skip-nx-cache --baseHref ${NX_DEPLOY_URL:-/} --deployUrl ${NX_DEPLOY_URL:-/}

      - name: Deploy to production
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: app.visian.org
          deploy_key: ${{ secrets.PROD_REPO_DEPLOY_KEY }}
          external_repository: HealthML/visian-prod
          publish_branch: main
          publish_dir: ./dist/apps/editor
          force_orphan: true
