name: Nx Affected CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: git fetch --no-tags --prune --depth=5 origin master
      - run: yarn install --frozen-lockfile
      - run: yarn affected:lint --base=origin/master
      - run: yarn affected:test --base=origin/master
      - run: yarn affected:compile --base=origin/master
      - run: yarn affected:build --prod --skip-nx-cache --baseHref ${NX_DEPLOY_URL:-/} --deployUrl ${NX_DEPLOY_URL:-/} --base=origin/master
      #- run: yarn affected:e2e --base=origin/master

      - uses: actions/upload-artifact@v2
        with:
          name: editor-build
          path: dist/apps/editor/
          if-no-files-found: ignore
          retention-days: 1

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: editor-build
      - name: Check if build exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "index.html"
      - name: Deploy to testing
        uses: peaceiris/actions-gh-pages@v3
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/editor
          force_orphan: true

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: editor-build
      - name: Check if build exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "index.html"
      - name: Deploy to production
        uses: peaceiris/actions-gh-pages@v3
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          cname: app.visian.org
          deploy_key: ${{ secrets.PROD_REPO_DEPLOY_KEY }}
          external_repository: HealthML/visian-prod
          publish_branch: main
          publish_dir: ./dist/apps/editor
          force_orphan: true
