name: Nx Affected CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: git fetch --no-tags --prune --depth=5 origin master
      - run: yarn install --frozen-lockfile
      - run: yarn affected:lint --base=origin/master
      - run: yarn affected:test --base=origin/master
      - run: yarn affected:compile --base=origin/master
      #- run: yarn affected:e2e --base=origin/master

  build:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - run: yarn affected:build --prod --skip-nx-cache --baseHref ${NX_DEPLOY_URL:-/} --deployUrl ${NX_DEPLOY_URL:-/} --base=origin/master

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/develop'

    steps:
      - name: Deploy to testing
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/editor
          force_orphan: true

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to production
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: app.visian.org
          deploy_key: ${{ secrets.PROD_REPO_DEPLOY_KEY }}
          external_repository: HealthML/visian-prod
          publish_branch: main
          publish_dir: ./dist/apps/editor
          force_orphan: true
